using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace imageboard.Models;

// TODO: Rename to Item? Item Container?

[Index(nameof(Hash), IsUnique = true)]
public class Item
{
     // AUTOGENERATED BY DB

    [Key]
    public int Id { get; set; }

    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public DateTime UploadDate { get; set; }
    //public DateTime UploadDate { get; set; } = DateTime.UtcNow;

    // COMPUTED BASED ON UPLOADED DATA

    [Required]
    [MaxLength(100)]
    public string FileType { get; set; } = string.Empty;

    public string Hash {get; set;} = string.Empty; // used to detect duplicate uploads

    [MaxLength(50)]
    public int? UploaderId { get; set; } = null; // displayed as "Anonymous" if null

    // OPTIONAL

    [MaxLength(5000)]
    public string Description { get; set; } = string.Empty;
        
    // NAVIGATION
    public List<ItemTag> ItemTags { get; set; } = new();
    
}